### ISSUE TITLE
How can i delete firstname-surname ?

### ISSUE THREAD

**Issue by dorukhan1** [techux/Mega-nz-Account-Creators#1]
Im using colab. It creating without problems but how can i delete first and surname ? I dont want username and surname when creating an account.

**Comment by techux** [comment]
Hi @dorukhan1 ,

To remove surname and username , you need to modify line number 118 as follow

From :
```python
account = f"{full_name}:{email}:{passwd}"
```
To :
```python
account = f"{email}:{passwd}"
```

Now, only email and password is saved and displayed. 

Thank you 
@techux
