### ISSUE TITLE
I cant install requirements

### ISSUE THREAD

**Issue by dorukhan1** [techux/Mega-nz-Account-Creators#2]
It's been giving an error here for 3 days and it won't create an account.

![Screenshot 2024-07-20 at 10-44-42 Mega_nz_Account_Generator_Colab ipynb - Colab](https://github.com/user-attachments/assets/db85224f-214b-4681-8aa6-c02b86f27a20)

**Comment by techux** [comment]
Hello @dorukhan1 
Recently I checked and everything works fine for me .
It might be the problem of colab runtime.

You may take the following steps :
1. Disconnect and delete runtime then run code again
2. Change the Google account if you have another
3. Run the Simple version of Bot on code editor .
[accountGenerator.py](https://github.com/techux/Mega-nz-Account-Creators/blob/main/accountGenerator.py)

Try this and update if you still face some problem.

Thank You

**Comment by dorukhan1** [comment]
Thanks !
